/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author sport
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        
        //this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboEquipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextDescuento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBotonComprar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboVoltaje = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextCantidadCDs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboCapacidadipod = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboTamanoTV = new javax.swing.JComboBox<>();
        jBotonSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo", "iPod", "TV" }));
        jComboEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEquipoActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecciona el aparato electronico:");

        jLabel2.setText("Ingrese el descuento asignado:");

        jLabel3.setText("%");

        jBotonComprar.setText("Comprar");
        jBotonComprar.setEnabled(false);
        jBotonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonComprarActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio del producto:");

        jLabel5.setText("Voltaje");

        jComboVoltaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "110", "220", "440" }));

        jLabel6.setText("Cantidad de CD's del Equipo:");

        jTextCantidadCDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCantidadCDsActionPerformed(evt);
            }
        });

        jLabel7.setText("Capacidad del iPod:");

        jComboCapacidadipod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "64 GB", "128 GB", "256 GB" }));

        jLabel8.setText("Tamaño del televisor:");

        jComboTamanoTV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30''", "32''", "36''", "48''" }));
        jComboTamanoTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTamanoTVActionPerformed(evt);
            }
        });

        jBotonSeleccionar.setText("Seleccionar");
        jBotonSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBotonSeleccionarMouseClicked(evt);
            }
        });
        jBotonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboEquipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBotonSeleccionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboCapacidadipod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextCantidadCDs)
                            .addComponent(jComboTamanoTV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jBotonComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotonSeleccionar))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextCantidadCDs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboCapacidadipod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboTamanoTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboVoltaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jBotonComprar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEquipoActionPerformed

    }//GEN-LAST:event_jComboEquipoActionPerformed

    private void jTextCantidadCDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCantidadCDsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCantidadCDsActionPerformed

    private void jComboTamanoTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTamanoTVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTamanoTVActionPerformed

    private void jBotonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSeleccionarActionPerformed

    }//GEN-LAST:event_jBotonSeleccionarActionPerformed

    private void jBotonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBotonComprarActionPerformed

    private void jBotonSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBotonSeleccionarMouseClicked
        if (jComboEquipo.getSelectedIndex()==0){
            jBotonComprar.setEnabled(true);
            jComboTamanoTV.setEnabled(false);
            jComboCapacidadipod.setEnabled(false);
            jTextCantidadCDs.setEnabled(true);
        } else if (jComboEquipo.getSelectedIndex()==1){
            jBotonComprar.setEnabled(true);
            jComboTamanoTV.setEnabled(false);
            jComboCapacidadipod.setEnabled(true);
            jTextCantidadCDs.setEnabled(false);
        } else if (jComboEquipo.getSelectedIndex()==2){
            jBotonComprar.setEnabled(true);
            jComboTamanoTV.setEnabled(true);
            jComboCapacidadipod.setEnabled(false);
            jTextCantidadCDs.setEnabled(false);
        }
        
    }//GEN-LAST:event_jBotonSeleccionarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBotonComprar;
    private javax.swing.JButton jBotonSeleccionar;
    public javax.swing.JComboBox<String> jComboCapacidadipod;
    public javax.swing.JComboBox<String> jComboEquipo;
    public javax.swing.JComboBox<String> jComboTamanoTV;
    public javax.swing.JComboBox<String> jComboVoltaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField jTextCantidadCDs;
    public javax.swing.JTextField jTextDescuento;
    public javax.swing.JTextField jTextPrecio;
    // End of variables declaration//GEN-END:variables
}
